githubToken: GitHub token (no scopes needed)
repository: jellyfin/jellyfin-android
milestone: v2.3.0

previousReleases:
  - v2.3.0-beta.1
  - v2.3.0-beta.2
  - v2.3.0-beta.3
  - v2.3.0-beta.4
  - v2.3.0-beta.5
  - v2.3.0-beta.6

ignoreLabels:
  - changelog-ignore

groups:
  - name: Highlights
    labels: [release-highlight]
  - type: changelog
  - name: Changelog
    type: leftover
  - name: Dependency updates
    type: dependencies
    labels: [dependencies]
    authors: ['renovate[bot]']

addContributors: true
addContributorCounts: false
